# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DBpopup.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import time
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QMovie


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 156)
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint | QtCore.Qt.WindowStaysOnTopHint)

        #self.progressBar = QtWidgets.QProgressBar(Form)
        #self.progressBar.setGeometry(QtCore.QRect(130, 90, 161, 23))
        #self.progressBar.setProperty("value", 24)
        #self.progressBar.setObjectName("progressBar")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(180, 80, 75, 40))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        #self.label_2.setGeometry(QtCore.QRect(25, 25, 200, 200))
        self.label_2.setMinimumSize(QtCore.QSize(48, 48))
        self.label_2.setMaximumSize(QtCore.QSize(48, 48))
        self.movie = QMovie("48x48.gif")
        self.label_2.setMovie(self.movie)
        self.movie.start()

        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 20, 371, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Refreshing DataBase"))
        self.label.setText(_translate("Form", "Please Wait for Database to finish Refreshing"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
